services:
  virbooks-app:
    build:
      context: ./virbooks-app
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./virbooks-app/.env
    volumes:
      - ./virbooks-app:/home/app
      - /home/app/node_modules
    depends_on:
      - virbooks-db
    ports:
      - "3000:3000"
    networks:
     - virbooks-net
    stdin_open: true
    tty: true

  virbooks-api:
    build:
      context: ./virbooks-api
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./virbooks-api/.env
    volumes:
      - "./virbooks-api:/home/app"
    depends_on:
      - virbooks-db
    ports:
      - "5050:5050"
    networks:
      - virbooks-net

  virbooks-db:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - db-data:/data/db
    networks:
      - virbooks-net

  mongo-express:
    image: mongo-express:1
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PASSWORD}
    depends_on:
      - virbooks-db
    networks:
      - virbooks-net

volumes:
  db-data:
    driver: local

networks:
  virbooks-net:
    driver: bridge