CODE_SUCCESS_ADD_BOOK = "SUCCESS_ADD_BOOK"
CODE_SUCCESS_GET_ALL_BOOKS = "SUCCESS_GET_ALL_BOOKS"
CODE_SUCCESS_GET_ALL_GENRES = "SUCCESS_GET_ALL_GENRES"
CODE_SUCCESS_DELETE_BOOK = "SUCCESS_DELETE_BOOK"

CODE_ERROR_API = "ERROR_INTERNAL_SERVER"
CODE_ERROR_PYDANTIC = "ERROR_PYDANTIC"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_BOOK_ALREADY_EXISTS = "ERROR_BOOK_ALREADY_EXISTS"

CODE_NOT_FOUND_BOOK = "NOT_FOUND_BOOK"
